config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root "home#index"
  get "saved_posts/index"
  
  resources :home, only: [] do
    collection do 
      get :search_user
      get :user_profile
    end  
  end 


  resources :notifications ,only: [:index]
  
  devise_for :users, controllers: {
    registrations: 'users/registrations',
        sessions: 'users/sessions',
        omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :posts do
    resources :comments, only: [:index, :create,:destroy]
    resources :likes, only: [:create, :index ] 
    resource :saved_posts,  only: [:create,:destroy]
  end

 
 
  resources :users, only: [:index, :show] do
    resources :follows, only: [] do
      collection do
        get :all_followers
        get :all_followed
        post :create_followed
        delete :destroy_followed
      end
    end
  end

  resources :conversations,only: [:index, :new, :create] do
    resources :messages ,only: [:index, :create]
   end
  

  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.admin?
      can :manage, :all 
    else 
      can :read, Post     
      can :create, Post  
      can :update, Post, user_id: user.id 
      can :destroy, Post, user_id: user.id 

      can :create, Comment  
      can :read , Comment
      can :destroy, Comment, user_id: user.id 

      can :read , SavedPost, user_id: user.id
      can :create ,SavedPost
      can :destroy, SavedPost, user_id: user.id 
    end
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
  def self.ransackable_attributes(_auth_object = nil)
    %w[id email created_at updated_at]
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
   belongs_to :user
   belongs_to :post
   validates :body, presence: true
   
end

app/models/conversation.rb
class Conversation < ApplicationRecord
    belongs_to :sender, :foreign_key => :sender_id, class_name: "User"
    belongs_to :recipient, :foreign_key => :recipient_id, class_name: "User"
    has_many :messages, dependent: :destroy
    validates_uniqueness_of :sender_id, :scope => :recipient_id
    scope :between, -> (sender_id,recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
    end
end

app/models/follow.rb
class Follow < ApplicationRecord
   belongs_to :follower, class_name: 'User'
   belongs_to :followed, class_name: 'User'
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates_uniqueness_of :user_id, :scope => :post_id
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :conversation
    belongs_to :user
    validates_presence_of :body, :conversation_id, :user_id
    
    def message_time
     created_at.strftime("%m/%d/%y at %l:%M %p")
    end
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image 
  has_many_attached :pictures
  belongs_to :user
  has_many :comments ,dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :saved_posts,dependent: :destroy
  validates :title,:body, presence: true
  validate :image_or_pictures_present

  def self.ransackable_attributes(_auth_object = nil)
    %w[user_id title body] 
  end
  
  def self.ransackable_associations(_auth_object = nil)
    [] 
  end

  private

  def image_or_pictures_present
    if image.blank? && pictures.blank?
      errors.add(:base, "Either image or pictures must be attached.")
    end
  end
end

app/models/saved_post.rb
class SavedPost < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates_uniqueness_of :user_id, :scope => :post_id
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]

  has_one_attached :profile_pic 
  has_many :posts, dependent: :destroy
  has_many :comments
  has_many :likes
  has_many :saved_posts, dependent: :destroy
  has_many :active_relationships, class_name: 'Follow', foreign_key: 'follower_id', dependent: :destroy, inverse_of: :follower
  has_many :followings, through: :active_relationships, source: :followed
  has_many :passive_relationships, class_name: 'Follow', foreign_key: 'followed_id', dependent: :destroy, inverse_of: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  validates :name, presence: true
  validates :profile_name, presence: true, uniqueness: true
  
  after_create :send_admin_mail

  def send_admin_mail
    UserMailer.welcome_email(self).deliver_now
  end

  def follow(user)
    active_relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    active_relationships.find_by(followed_id: user.id)&.destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.ransackable_attributes(_auth_object = nil)
    %w[name email]
  end
  
  def self.ransackable_associations(_auth_object = nil)
    []
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name
      user.profile_name = auth.info.name
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    user_ids = current_user.followings.pluck(:id) + current_user.followers.pluck(:id)
    user_ids << current_user.id
    @posts = Post.where(user_id: user_ids.uniq).includes(:user).order(created_at: :desc)

  end

  def user_profile 
    @days_since_created = (Date.today - current_user.created_at.to_date).to_i
    @posts = current_user.posts.all.order(created_at: :desc)

  end

  def search_user
    if params[:title].present?
      @users = User.where("profile_name Like ?", "%#{params[:title]}%")
      @posts = Post.where("body Like ?", "%#{params[:title]}%")
     else
        flash[:errors] = "We Couldn't find your request."
    end 
  end 
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/saved_posts_helper.rb
module SavedPostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/shared/_home_header.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Page Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "heder" %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>

<body>
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button> 

        <div class="sidebar">
            <ul>
                <li class="nav-item">
                    <div class="inline-items">
                        <i class="fa fa-fw fa-home"></i>
                        <%= link_to "Home", root_path, class: 'nav-link' %>
                    </div>
                </li>

                <li class="nav-item">
                    <div class="inline-items">
                        <i class="fa fa-fw fa-user-circle"></i>
                        <%= link_to "My Profile", user_profile_home_index_path, class: 'nav-link' %> 
                    </div>
                </li>

                <li class="nav-item">
                    <div class="inline-items">
                        <i class="fas fa-user-edit"></i>
                        <%= link_to "Profile Edit", edit_user_registration_path, class: 'nav-link' %> 
                    </div>
                </li>

                <li class="nav-item">
                    <div class="inline-items">
                        <i class="material-icons">add_to_photos</i>
                        <%= link_to "Add Post", new_post_path, class: 'nav-link' %> 
                    </div>
                </li>
                <% if current_user.admin? %>
                <li class="nav-item">
                    <div class="inline-items">
                        <i class="fas fa-user-graduate"></i>
                        <%= link_to "Admin Pannel", admin_users_path, class: 'nav-link' %> 
                    </div>
                </li>
                <% end %>
                <li class="nav-item">
                    <div class="inline-items">
                        <i class="fas fa-images"></i>
                        <%= link_to "Save Posts", saved_posts_index_path, class: 'nav-link' %> 
                    </div>
                </li>

                <li class="nav-item">
                    <div class="inline-items">
                        <i class="material-icons">message</i>
                        <%= link_to "Messages", conversations_path, data: { turbo_method: :get }, class: 'nav-link' %> 
                    </div>
                </li>

                <li class="nav-item">
                    <div class="inline-items">
                        <i class="fas fa-atom"></i>
                        <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete }, class: 'nav-link' %> 
                    </div>
                </li>
            </ul>

            <%= form_with url: search_user_home_index_path, method: :get do |form| %>
                <div>
                    <%= form.label :title %><br>
                    <%= form.text_field :title %>
                </div>

                <div id="submit">
                    <%= form.submit "Search" %>
                </div>
            <% end %>

            <span class="navbar-text"></span>
        </div>
    </div>
</body>
</html>

app/views/shared/_links.html.erb
<%- resource_class.omniauth_providers.each do |provider|%>
  <%= form_for "Login",
      url: omniauth_authorize_path(resource_name, provider),
      method: :post,
      data: {turbo: "false"} do |f| %>
        <%= f.submit_to "login", type: "image", src: url_for("/assets/btn_google_auth")%>
    <%end%>
  <%end%>

app/views/shared/_post_form.html.erb
<div id="post_page">

  <div class= "heding_post_form">
    <h1 class= "post_heading">New Post</h1>
  
  <%= form_with model: @post  do |form| %>
      <div>
        <%= form.label :title %><br>
        <%= form.text_field :title %>
      </div>

      <div>
        <%= form.label :body %><br>
        <%= form.text_area :body %><br>
      </div>

      <div>
        <%= form.label :image  %><br>
        <%= form.file_field :image  %><br>
      </div>

      <div>
        <%= form.label :pictures %><br>
        <%= form.file_field :pictures, multiple: true %><br>
      </div>

      <div id="submit_button">
        <%= form.submit "Create Post"%>
      </div>
      </div>

  <% end %>

</div>