config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root "home#index"
  get "saved_posts/index"
  
  resources :home, only: [] do
    collection do 
      get :search_user
      get :user_profile
    end  
  end 


  resources :notifications ,only: [:index]
  
  devise_for :users, controllers: {
    registrations: 'users/registrations',
        sessions: 'users/sessions',
        omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :posts do
    resources :comments, only: [:index, :create,:destroy]
    resources :likes, only: [:create, :index ] 
    resource :saved_posts,  only: [:create,:destroy]
  end

 
 
  resources :users, only: [:index, :show] do
    resources :follows, only: [] do
      collection do
        get :all_followers
        get :all_followed
        post :create_followed
        delete :destroy_followed
      end
    end
  end

  resources :conversations,only: [:index, :new, :create] do
    resources :messages ,only: [:index, :create]
   end
  

  get "up" => "rails/health#show", as: :rails_health_check
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.admin?
      can :manage, :all 
    else 
      can :read, Post     
      can :create, Post  
      can :update, Post, user_id: user.id 
      can :destroy, Post, user_id: user.id 

      can :create, Comment  
      can :read , Comment
      can :destroy, Comment, user_id: user.id 

      can :read , SavedPost, user_id: user.id
      can :create ,SavedPost
      can :destroy, SavedPost, user_id: user.id 
    end
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
  def self.ransackable_attributes(_auth_object = nil)
    %w[id email created_at updated_at]
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
   belongs_to :user
   belongs_to :post
   validates :body, presence: true
   
end

app/models/conversation.rb
class Conversation < ApplicationRecord
    belongs_to :sender, :foreign_key => :sender_id, class_name: "User"
    belongs_to :recipient, :foreign_key => :recipient_id, class_name: "User"
    has_many :messages, dependent: :destroy
    validates_uniqueness_of :sender_id, :scope => :recipient_id
    scope :between, -> (sender_id,recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
    end
end

app/models/follow.rb
class Follow < ApplicationRecord
   belongs_to :follower, class_name: 'User'
   belongs_to :followed, class_name: 'User'
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates_uniqueness_of :user_id, :scope => :post_id
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :conversation
    belongs_to :user
    validates_presence_of :body, :conversation_id, :user_id
    
    def message_time
     created_at.strftime("%m/%d/%y at %l:%M %p")
    end
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image 
  has_many_attached :pictures
  belongs_to :user
  has_many :comments ,dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :saved_posts,dependent: :destroy
  validates :title,:body, presence: true
  validate :image_or_pictures_present

  def self.ransackable_attributes(_auth_object = nil)
    %w[user_id title body] 
  end
  
  def self.ransackable_associations(_auth_object = nil)
    [] 
  end

  private

  def image_or_pictures_present
    if image.blank? && pictures.blank?
      errors.add(:base, "Either image or pictures must be attached.")
    end
  end
end

app/models/saved_post.rb
class SavedPost < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates_uniqueness_of :user_id, :scope => :post_id
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]

  has_one_attached :profile_pic 
  has_many :posts, dependent: :destroy
  has_many :comments
  has_many :likes
  has_many :saved_posts, dependent: :destroy
  has_many :active_relationships, class_name: 'Follow', foreign_key: 'follower_id', dependent: :destroy, inverse_of: :follower
  has_many :followings, through: :active_relationships, source: :followed
  has_many :passive_relationships, class_name: 'Follow', foreign_key: 'followed_id', dependent: :destroy, inverse_of: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  validates :name, presence: true
  validates :profile_name, presence: true, uniqueness: true
  
  after_create :send_admin_mail

  def send_admin_mail
    UserMailer.welcome_email(self).deliver_now
  end

  def follow(user)
    active_relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    active_relationships.find_by(followed_id: user.id)&.destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.ransackable_attributes(_auth_object = nil)
    %w[name email]
  end
  
  def self.ransackable_associations(_auth_object = nil)
    []
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name
      user.profile_name = auth.info.name
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    user_ids = current_user.followings.pluck(:id) + current_user.followers.pluck(:id)
    user_ids << current_user.id
    @posts = Post.where(user_id: user_ids.uniq).includes(:user).order(created_at: :desc)

  end

  def user_profile 
    @days_since_created = (Date.today - current_user.created_at.to_date).to_i
    @posts = current_user.posts.all.order(created_at: :desc)

  end

  def search_user
    if params[:title].present?
      @users = User.where("profile_name Like ?", "%#{params[:title]}%")
      @posts = Post.where("body Like ?", "%#{params[:title]}%")
     else
        flash[:errors] = "We Couldn't find your request."
    end 
  end 
end 

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def index
    @likes = Post.find(params[:post_id]).likes.where(like: true)
  end

  def create
    post = Post.find(params[:post_id])
    like = current_user.likes.find_or_initialize_by(post: post)
    like.like = !like.like

    if like.save
      redirect_to request.referer
    else
      redirect_to root_path, alert: "There was an error."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/conversation_helper.rb
module ConversationHelper
 
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/saved_posts_helper.rb
module SavedPostsHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Page Title</title>
    <%= stylesheet_link_tag "home" %>
    <%= javascript_include_tag 'slideshow' %>
</head>
<body>

    <div id="parent_div">
        <div id="child_div">
            <% @posts.each do |post| %>
                <div class="profile-container">
                    <div id="profile_pic">
                        <% if post.user.profile_pic.attached? %>
                            <%= image_tag post.user.profile_pic, class: "profile-pic" %>
                        <% end %>
                    </div>

                    <h4 id="profile_name"><%= post.user.profile_name %></h4>

                    <% unless current_user.id == post.user.id %>
                        <% if current_user.following?(post.user) %>
                            <%= link_to 'Unfollow', destroy_followed_user_follows_path(user_id: post.user.id), remote: true, data: { turbo_method: :delete }, class: "action-link" %>
                        <% else %>
                            <%= link_to 'Follow', create_followed_user_follows_path(user_id: post.user.id), remote: true, data: { turbo_method: :post }, class: "action-link" %>
                        <% end %>
                    <% end %>
                </div>

                <h2><%= post.title %></h2>

                <% if post.image.image? %>
                    <%= image_tag post.image, style: "max-height:400px; width:100%" %>
                <% elsif post.image.video? %>
                    <%= video_tag post.image, controls: true %>
                <% end %>

                <div class="w3-content w3-display-container">
                    <% post.pictures.each_with_index do |picture, index| %>
                        <% if picture.image? %>
                            <img class="mySlides" src="<%= url_for(picture) %>" style="width:100%; display:none;" />
                        <% end %>
                    <% end %>

                    <% if post.pictures.count > 1 %>
                        <button class="w3-button w3-black w3-display-left" onclick="plusDivs(-1)">&#10094;</button>
                        <button class="w3-button w3-black w3-display-right" onclick="plusDivs(1)">&#10095;</button>
                    <% end %>
                </div>

                <p><%= post.body %></p>

                <div class="post-actions">
                    <h4>
                        <% like = current_user.likes.find_by(post: post) %>
                        <% if like && like.like %>
                            <%= button_to post_likes_path(post), data: { turbo_method: "post" }, class: "btn-icon-like" do %>
                                <i class='fas fa-heart'></i>
                            <% end %>
                        <% else %>
                            <%= button_to post_likes_path(post), data: { turbo_method: "post" }, class: "btn-iconfg" do %>
                                <i class='far fa-heart'></i>
                            <% end %>
                        <% end %>

                        <%= link_to "Likes: #{post.likes.where(like: true).count}", post_likes_path(post), data: { turbo_method: "get" }, class: "action-link" %>
                    </h4>

                    <div class="dropdown">
                        <button class="btn btn-secondary dropdown-toggle action-button" type="button" id="dropdownMenuButton2" data-bs-toggle="dropdown" aria-expanded="false">
                            Create Comment
                        </button>
                        <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdownMenuButton2">
                            <%= form_with model: [post, post.comments.build] do |form| %>
                                <li><%= form.text_field :body, placeholder: "Add a comment..." %></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><%= form.submit %></li>
                            <% end %>
                        </ul>
                    </div>

                    <h4>
                        <%= link_to "Comments: #{post.comments.count}", post_comments_path(post), data: { turbo_method: "get" }, class: "action-link" %>
                    </h4>

                    <% if current_user.saved_posts.where(post_id: post.id).present? %>
                        <%= button_to "Delete Save Post", post_saved_posts_path(post), method: :delete, data: { turbo: false }, class: 'delete-button' %>
                    <% else %>
                        <%= button_to 'Save', post_saved_posts_path(post), data: { turbo_method: "post" }, class: "action-button" %>
                    <% end %>
                </div>

                <hr class="custom-hr">
            <% end %>
        </div>
    </div>

</body>
</html>

app/views/home/search_user.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Title of the document</title>
  <%= javascript_include_tag 'slideshow' %>
</head>
<body>
  <div>
    <div>
      <% if @users.present? %>
        <ul>
          <% @users.each do |user| %>
            <li>
              <div class="profile-container">
                <div id="profile_pic">
                  <% if user.profile_pic.attached? %>
                    <%= image_tag user.profile_pic, class: "profile-pic" %>
                  <% end %>
                </div>

                <h1 id="profile_name"><%= user.profile_name %></h1>
                
                <% unless current_user == user %>
                  <% if current_user.following?(user) %>
                    <%= link_to 'Unfollow', destroy_followed_user_follows_path(user_id: user.id), remote: true, data: { turbo_method: :delete }, class: "action-link" %>
                  <% else %>
                    <%= link_to 'Follow', create_followed_user_follows_path(user_id: user.id), remote: true, data: { turbo_method: :post }, class: "action-link" %>
                  <% end %>
                <% end %>
              </div>
            </li>
          <% end %>
        </ul>
      
      <% elsif @posts.present? %>
        <div id="parent_div">
          <div id="child_div">
            <% @posts.each do |post| %>
              <div class="profile-container">
                <div id="profile_pic">
                  <% if User.find(post.user_id).profile_pic.attached? %>
                    <%= image_tag User.find(post.user_id).profile_pic, class: "profile-pic" %>
                  <% end %>
                </div>

                <h4 id="profile_name"><%= User.find(post.user_id).profile_name %></h4>
                
                <% unless current_user.id == post.user.id %>
                  <% if current_user.following?(User.find(post.user.id)) %>
                    <%= link_to 'Unfollow', destroy_followed_user_follows_path(user_id: post.user.id), remote: true, data: { turbo_method: :delete }, class: "action-link" %>
                  <% else %>
                    <%= link_to 'Follow', create_followed_user_follows_path(user_id: post.user.id), remote: true, data: { turbo_method: :post }, class: "action-link" %>
                  <% end %>
                <% end %>
              </div>

              <% if post.image.image? %>
                <%= image_tag post.image, style: "max-height:400px; width:100%" %>
              <% elsif post.image.video? %>
                <%= video_tag post.image, controls: true %>
              <% end %>

              <div class="w3-content w3-display-container">
                <% post.pictures.each_with_index do |picture, index| %>
                  <% if picture.image? %>
                    <img class="mySlides" src="<%= url_for(picture) %>" style="width:100%; display:none;" />
                  <% end %>
                <% end %>

                <% if post.pictures.count > 1 %>
                  <button class="w3-button w3-black w3-display-left" onclick="plusDivs(-1)">&#10094;</button>
                  <button class="w3-button w3-black w3-display-right" onclick="plusDivs(1)">&#10095;</button>
                <% end %>
              </div>

              <div class="post-actions">
                <h4>
                  <% like = current_user.likes.find_by(post: post) %>
                  <% if like && like.like %>
                    <%= button_to 'Unlike', post_likes_path(post), data: { turbo_method: "post" }, class: "action-button" %>
                  <% else %>
                    <%= button_to 'Like', post_likes_path(post), data: { turbo_method: "post" }, class: "action-button" %>
                  <% end %>

                  <%= link_to "Likes: #{post.likes.where(like: true).count}", post_likes_path(post), data: { turbo_method: "get" }, class: "action-link" %>
                </h4>

                <div class="dropdown">
                  <button class="btn btn-secondary dropdown-toggle action-button" type="button" id="dropdownMenuButton2" data-bs-toggle="dropdown" aria-expanded="false">
                    Create Comment
                  </button>
                  <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdownMenuButton2">
                    <%= form_with model: [post, post.comments.build] do |form| %>
                      <li><%= form.text_field :body %></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><%= form.submit %></li>
                    <% end %>
                  </ul>
                </div>

                <h4>
                  <%= link_to "Comments: #{post.comments.count}", post_comments_path(post), data: { turbo_method: "get" }, class: "action-link" %>
                </h4>

                <%= button_to 'Save', post_saved_posts_path(post), data: { turbo_method: "post" }, class: "action-button" %>
              </div>
              <hr class="custom-hr">
            <% end %>
          </div>
        </div>
      <% else %>
        <h3><%= flash[:errors] %></h3>
      <% end %>
    </div>
  </div>
</body>
</html>

app/views/home/user_profile.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Page Title</title>
    <%= javascript_include_tag 'slideshow' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
</head>
<body>

   
    <div id="parent_div">
        <div id="child_div">
            <div class="profile-container">
                <div id="profile_pic">
                    <% if current_user.profile_pic.attached? %>
                        <%= image_tag current_user.profile_pic, class: "profile-pic" %>
                    <% end %>
                </div>
                <h1 id="profile_name"><%= current_user.profile_name %></h1>
                 <h3> <i class='fas fa-calendar-alt'></i><%= @days_since_created %> </h3>
            </div>
            
            <%= link_to "Followers: #{current_user.followers.count}", all_followers_user_follows_path(current_user) %>
            <%= link_to "Following: #{current_user.followings.count}", all_followed_user_follows_path(current_user) %>
          
              <hr class="custom-hr">
           <% @posts.each do |post| %>

                <h2>  <%= post.title %></h2>
                <% if post.image.image? %>
                    <%= image_tag post.image, style: "max-height:400px; width:100%"%>
                <% elsif post.image.video? %>
                    <%= video_tag post.image, controls: true %>
                <% end %>

                <div class="w3-content w3-display-container">
                    <% post.pictures.each_with_index do |picture, index| %>
                        <% if picture.image? %>
                            <img class="mySlides" src="<%= url_for(picture) %>" style="width:100%; display:none;" />
                        <% end %>
                    <% end %>

                    <% if post.pictures.count > 1 %> 
                        <button class="w3-button w3-black w3-display-left" onclick="plusDivs(-1)">&#10094;</button>
                        <button class="w3-button w3-black w3-display-right" onclick="plusDivs(1)">&#10095;</button>
                    <% end %>
                </div>
                <p> <%= post.body %></p>
             <div class="post-actions">
                <h4>
                    <% like = current_user.likes.find_by(post: post) %>
                    <% if like && like.like %>
                        <%= button_to  post_likes_path(post), data: { turbo_method: "post" } ,class: "btn-icon-like" do %>
                        <i class='fas fa-heart' ></i>
                        <%end %>
                    <% else %>
                         <%= button_to  post_likes_path(post), data: { turbo_method: "post" } ,class: "btn-iconfg" do %>
                        <i class='far fa-heart' ></i>
                        <%end %>
                    <% end %>

                    <%= link_to "Likes: #{post.likes.where(like: true).count}", post_likes_path(post), data: { turbo_method: "get" } %>
                </h4>

                <div class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton2" data-bs-toggle="dropdown" aria-expanded="false">
                        Create Comment
                    </button>
                    <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="dropdownMenuButton2">
                        <%= form_with model: [post, post.comments.build] do |form| %>
                            <li><%= form.text_field :body,placeholder: "Add a comment..."  %></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><%= form.submit %></li>
                        <% end %>
                    </ul>
                </div>

                <h4><%= link_to "Comments: #{post.comments.count}", post_comments_path(post), data: { turbo_method: "get" } %></h4>
            

              <%= button_to post_path(post), method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "btn-icon-delete" do %>
                 <i class="material-icons">delete</i>
                <% end %>

          
                <%= button_to edit_post_path(post), method: :get, class: "btn btn-primary" do %>
                  <i class="far fa-edit"></i>
                <% end %>


                </div>
                 <hr class="custom-hr">

            <% end %>

        </div>
    </div>

</body>
</html>